### ISSUE TITLE
Unable to set ports with NodePort

### ISSUE THREAD

**Issue by serenewaffles** [blakeblackshear/blakeshome-charts#10]
I am unable to get Kubernetes to assign my requested port. The relevant part of my helm frigate.yaml is

```
service:
  type: NodePort
  selector:
    app: frigate
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30598
```
I have also tried
```
service:
  type: NodePort
  port: 5000
  nodePort: 30598
```
Kubernetes simply assigns random ports to forward to both 5000 and 1935
