### ISSUE TITLE
mountPath wrong in frigate docker image 0.12.1

### ISSUE THREAD

**Issue by bobslaede** [blakeblackshear/blakeshome-charts#57]
The chart will mount the data dir to `/data`, but the frigate docker image will use `/media` as the storage location.  

Temporary fix, in values.yaml:
```yaml
extraVolumeMounts:
  - mountPath: /media
    name: data
```
