### ISSUE TITLE
Include port 8971 required for authentication mechanism

### ISSUE THREAD

**Issue by maxim-mityutko** [blakeblackshear/blakeshome-charts#74]
Frigate 0.14.0 introduced new port that should be used with authentication: https://docs.frigate.video/configuration/authentication

The following changes are required in the chart:

- add port 8971 into the Deployment manifest
- add new service to expose port 8971
- possibility to specify target service for Ingress to either point to non-auth service at port 5000 or to the newly added port 8971

**Comment by JL421** [comment]
Looking through your request because I enabled auth following your changes:

- TLS ingress is broken initially, the user will either need to feed the cert to the Frigate container, or disable TLS in their config
- If the user has the Home Assistant integration they'll either need a separate LB Service or Ingress on the unauthed port to continue using HA, unless there is a way to pass authentication to HA?

**Comment by maxim-mityutko** [comment]
- Indeed, I ended up disabling TLS in my setup. Maybe I can add a link to [TLS](https://docs.frigate.video/configuration/tls/) docs. Or in the [config example](https://github.com/blakeblackshear/blakeshome-charts/blob/f5e48b2161b65749dff2822e821e715e16e33fd6/charts/frigate/values.yaml#L62) in values.yaml
- Currently Frigate [docs ](https://docs.frigate.video/integrations/home-assistant#configuration)specifically mention that integration should point to an unauthenticated port. I won't be surprised if auth support might be somewhere on the roadmap. Of course it's not a problem if HASS is not running on the `hostNetwork: true`, then the traffic will just go to an internal service.

**Comment by jftanner** [comment]
Until your PR gets merged, I've got a workaround in place for my installation. I'll document the relevant bits here, in case they help anyone.

- `update.sh` just runs the helm command to install/upgrade frigate:
  ```sh
  #!/usr/bin/bash
  helm upgrade -i frigate blakeblackshear/frigate \
    --namespace frigate \
    --create-namespace \
    --values values.yaml \
    --set-file config=config.yaml \
    --post-renderer ./post-render.sh \
    --wait --timeout 3m
  ```
- `post-render.sh` (used by helm from `--post-renderer` uses kustomize to apply a patch:
  ```shell
  #!/bin/bash
  
  # Write the helm output to the kustomize directory.
  cat <&0 > kustomize/helm-output.yaml
  
  # Run kustomize.
  kustomize build kustomize
  
  # Clean up.
  rm kustomize/helm-output.yaml
  ```
- `kustomize/kustomize.yaml` takes in the helm output and applies patches:
  ```yaml
  resources:
    - helm-output.yaml
  
  patchesStrategicMerge:
    - patch.yaml
  ```
- `kustomize/patch.yaml` adds the missing port to the deployment and service:
  ```yaml
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: frigate
  spec:
    template:
      spec:
        containers:
          - name: frigate
            ports:
              - name: auth
                containerPort: 8971
  ---
  apiVersion: v1
  kind: Service
  metadata:
    name: frigate
  spec:
    ports:
      - name: auth
        port: 8971
        targetPort: auth
  ```

Note: I'm running Authentik, so the built-in self-signed TLS cert is fine for my needs. And they're running on the same cluster, so I just proxy `https://frigate.frigate.svc.cluster.local` instead of needing to expose an ingress. If you need the ingress (for using the built-in auth, or if your proxy is on a different system) you could enable and patch that as well.
