### ISSUE TITLE
Config file is read-only, unable to migrate config file.

### ISSUE THREAD

**Issue by XDDK** [blakeblackshear/blakeshome-charts#78]
I've tried everything in the world to make the config file not read-only so that it's editable from the UI. How can I fix this?

tried with full rights to the container, giving exisiting pvc, no pvc defaulting to emptyDir and nothing worked.
```
securityContext:
  runAsNonRoot: false
  privileged: true
  runAsUser: 0
  runAsGroup: 0
```
