### ISSUE TITLE
PR: allow NFS mounting on /media

### ISSUE THREAD

**Issue by jahegu** [blakeblackshear/blakeshome-charts#94]
On docker it is possible to use external NFS mounted volume on /media folder.

On chart mount external volume on /media is impossible as it is set to emptyDir when media persistence is disabled.

**Comment by beauwest** [comment]
I agree first-class support would make this easier, but you can also use an existing claim

```yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-media
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  mountOptions:
  - nfsvers=4.1
  nfs:
    server: 192.168.1.51
    path: /volume1/surveillance/Frigate
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: frigate-media
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: frigate-media
```

```yaml
    persistence:
      media:
        enabled: true
        existingClaim: frigate-media
```
